/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Chris Sweetwood (https://sketchfab.com/ChrisSweetwood)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/computer-terminal-b3a26b00c5b04eedad0a1cdca884130f
Title: Computer Terminal
*/
import { useGLTF } from "@react-three/drei";

export function Conmputer(props) {
  const { nodes, materials } = useGLTF("./computer_terminal.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, -5.3734, -41.8666]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={120.5716}
          >
            <mesh
              geometry={nodes.Plane_ShadowMaterial_0.geometry}
              material={materials.ShadowMaterial}
            />
            <mesh
              geometry={nodes.Plane_BackgroundMaterial_0.geometry}
              material={materials.BackgroundMaterial}
            />
          </group>
          <mesh
            geometry={nodes.Comp_Screen000_TerminalMaterial_0.geometry}
            material={materials.TerminalMaterial}
            position={[18.1613, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={212.25}
          />
          <mesh
            geometry={nodes.Comp_Screen002_TerminalMaterial_0.geometry}
            material={materials.TerminalMaterial}
            position={[18.1613, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={212.25}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./computer_terminal.glb");
